#ifndef _LaplacesDemonCpp_laplacesdemon_H
#define _LaplacesDemonCpp_laplacesdemon_H

#include <RcppArmadillo.h>

RcppExport SEXP mcmcamwg(SEXP MODEL, SEXP DATA, SEXP ITERATIONS, SEXP STATUS, SEXP THINNING, SEXP SPECS, SEXP ACCEPTANCE, SEXP DEV, SEXP DIAGCOVAR, SEXP liv, SEXP MON, SEXP MO0, SEXP SCALEF, SEXP THINNED, SEXP TUNING);

RcppExport SEXP mcmcmwg(SEXP MODEL, SEXP DATA, SEXP ITERATIONS, SEXP STATUS, SEXP THINNING, SEXP SPECS, SEXP ACCEPTANCE, SEXP DEV, SEXP DIAGCOVAR, SEXP liv, SEXP MON, SEXP MO0, SEXP SCALEF, SEXP THINNED, SEXP TUNING);

#endif
